import type { RoadmapContent } from '@/types/database';

/**
 * Generate Markdown from roadmap content
 */
export function generateMarkdown(roadmap: RoadmapContent, metadata?: {
    type: string;
    intensity: string;
    targetRole: string;
}): string {
    let markdown = '';

    // Title and Description
    markdown += `# ${roadmap.title}\n\n`;
    markdown += `${roadmap.description}\n\n`;

    // Metadata
    if (metadata) {
        markdown += `## Overview\n\n`;
        markdown += `- **Path**: ${metadata.type.replace('_', ' ')}\n`;
        markdown += `- **Intensity**: ${metadata.intensity}\n`;
        markdown += `- **Target Role**: ${metadata.targetRole}\n`;
        markdown += `- **Duration**: ${roadmap.totalWeeks} weeks (${roadmap.durationMonths} months)\n`;
        markdown += `- **Time Commitment**: ${roadmap.hoursPerDay} hours/day\n`;
        markdown += `- **Total Hours**: ~${roadmap.estimatedTotalHours} hours\n\n`;
    }

    // Key Skills
    markdown += `## Key Skills You'll Learn\n\n`;
    roadmap.keySkills.forEach(skill => {
        markdown += `- ${skill}\n`;
    });
    markdown += `\n`;

    // Tools & Platforms
    markdown += `## Tools & Platforms\n\n`;
    roadmap.toolsAndPlatforms.forEach(tool => {
        markdown += `- ${tool}\n`;
    });
    markdown += `\n`;

    // Milestones
    markdown += `## Week-by-Week Roadmap\n\n`;

    roadmap.milestones.forEach(milestone => {
        markdown += `### Week ${milestone.week}: ${milestone.title}\n\n`;
        markdown += `**Phase**: ${milestone.phase}\n\n`;
        markdown += `${milestone.description}\n\n`;

        // Learning Objectives
        markdown += `#### Learning Objectives\n\n`;
        milestone.learningObjectives.forEach(obj => {
            markdown += `- ${obj}\n`;
        });
        markdown += `\n`;

        // Tasks
        markdown += `#### Tasks\n\n`;
        milestone.tasks.forEach((task, idx) => {
            markdown += `##### ${idx + 1}. ${task.title}\n\n`;
            markdown += `**Type**: ${task.type.replace('_', ' ')} | **Time**: ${task.estimatedHours}h | **Priority**: ${task.priority}\n\n`;
            markdown += `${task.description}\n\n`;

            // Resources
            if (task.resources.length > 0) {
                markdown += `**Resources**:\n`;
                task.resources.forEach(resource => {
                    const freeTag = resource.isFree ? ' (Free)' : '';
                    markdown += `- [${resource.title}](${resource.url})${freeTag} - ${resource.platform}\n`;
                });
                markdown += `\n`;
            }

            markdown += `**Deliverable**: ${task.deliverable}\n\n`;
            markdown += `**Success Criteria**: ${task.successCriteria}\n\n`;
        });

        // Weekly Goal
        markdown += `#### Weekly Goal\n\n`;
        markdown += `${milestone.weeklyGoal}\n\n`;

        // Time Allocation
        markdown += `#### Time Allocation\n\n`;
        markdown += `- Learning: ${milestone.timeAllocation.learning}h\n`;
        markdown += `- Practice: ${milestone.timeAllocation.practice}h\n`;
        markdown += `- Projects: ${milestone.timeAllocation.projects}h\n`;
        markdown += `- Networking: ${milestone.timeAllocation.networking}h\n\n`;

        markdown += `---\n\n`;
    });

    // Success Metrics
    markdown += `## Success Metrics\n\n`;
    roadmap.successMetrics.forEach(metric => {
        markdown += `- ${metric}\n`;
    });
    markdown += `\n`;

    // Tips
    markdown += `## Pro Tips\n\n`;
    roadmap.tips.forEach(tip => {
        markdown += `- ${tip}\n`;
    });
    markdown += `\n`;

    markdown += `---\n\n`;
    markdown += `*Generated by Skill Lover - Your AI Career Architect*\n`;

    return markdown;
}

/**
 * Download markdown as file
 */
export function downloadMarkdown(content: string, filename: string) {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${filename}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

/**
 * Copy markdown to clipboard
 */
export async function copyMarkdownToClipboard(content: string): Promise<void> {
    try {
        await navigator.clipboard.writeText(content);
    } catch (error) {
        // Fallback for older browsers
        const textArea = document.createElement('textarea');
        textArea.value = content;
        textArea.style.position = 'fixed';
        textArea.style.left = '-999999px';
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
    }
}
