import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import type { RoadmapContent } from '@/types/database';

// Define styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 11,
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 24,
    marginBottom: 10,
    fontWeight: 'bold',
    color: '#7c3aed',
  },
  subtitle: {
    fontSize: 12,
    marginBottom: 20,
    color: '#666',
  },
  section: {
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: 16,
    marginBottom: 8,
    fontWeight: 'bold',
    color: '#333',
  },
  subsectionTitle: {
    fontSize: 14,
    marginBottom: 6,
    fontWeight: 'bold',
    color: '#444',
  },
  text: {
    fontSize: 11,
    marginBottom: 4,
    lineHeight: 1.5,
  },
  bulletPoint: {
    fontSize: 11,
    marginBottom: 3,
    marginLeft: 15,
    lineHeight: 1.4,
  },
  metadataRow: {
    flexDirection: 'row',
    marginBottom: 4,
  },
  metadataLabel: {
    fontWeight: 'bold',
    width: 120,
  },
  metadataValue: {
    flex: 1,
  },
  weekHeader: {
    backgroundColor: '#7c3aed',
    color: 'white',
    padding: 8,
    marginTop: 15,
    marginBottom: 8,
    fontSize: 14,
    fontWeight: 'bold',
  },
  taskCard: {
    border: '1px solid #e5e7eb',
    padding: 10,
    marginBottom: 8,
    backgroundColor: '#f9fafb',
  },
  taskTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  taskMeta: {
    fontSize: 9,
    color: '#666',
    marginBottom: 4,
  },
  resourceLink: {
    fontSize: 9,
    color: '#2563eb',
    marginLeft: 15,
    marginBottom: 2,
  },
  timeAllocation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f3f4f6',
    padding: 8,
    marginTop: 8,
  },
  timeItem: {
    fontSize: 9,
    textAlign: 'center',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#999',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 30,
    right: 40,
    fontSize: 9,
    color: '#999',
  },
});

interface RoadmapPDFProps {
  roadmap: RoadmapContent;
  metadata?: {
    type: string;
    intensity: string;
    targetRole: string;
  };
}

export const RoadmapPDF: React.FC<RoadmapPDFProps> = ({ roadmap, metadata }) => (
  <Document>
    {/* Cover Page */}
    <Page size="A4" style={styles.page}>
      <View style={{ marginTop: 100, textAlign: 'center' }}>
        <Text style={[styles.title, { fontSize: 32, marginBottom: 20 }]}>
          {roadmap.title}
        </Text>
        <Text style={[styles.subtitle, { fontSize: 14 }]}>
          {roadmap.description}
        </Text>
      </View>

      {metadata && (
        <View style={{ marginTop: 60 }}>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Path:</Text>
            <Text style={styles.metadataValue}>{metadata.type.replace('_', ' ')}</Text>
          </View>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Intensity:</Text>
            <Text style={styles.metadataValue}>{metadata.intensity}</Text>
          </View>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Target Role:</Text>
            <Text style={styles.metadataValue}>{metadata.targetRole}</Text>
          </View>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Duration:</Text>
            <Text style={styles.metadataValue}>
              {roadmap.totalWeeks} weeks ({roadmap.durationMonths} months)
            </Text>
          </View>
          <View style={styles.metadataRow}>
            <Text style={styles.metadataLabel}>Time Commitment:</Text>
            <Text style={styles.metadataValue}>{roadmap.hoursPerDay} hours/day</Text>
          </View>
        </View>
      )}

      <Text style={styles.footer}>Generated by RoadmapAI</Text>
    </Page>

    {/* Skills & Tools Page */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Key Skills You'll Learn</Text>
        {roadmap.keySkills.map((skill, index) => (
          <Text key={index} style={styles.bulletPoint}>• {skill}</Text>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Tools & Platforms</Text>
        {roadmap.toolsAndPlatforms.map((tool, index) => (
          <Text key={index} style={styles.bulletPoint}>• {tool}</Text>
        ))}
      </View>

      <Text style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} fixed />
    </Page>

    {/* Milestones Pages */}
    {roadmap.milestones.map((milestone, milestoneIndex) => (
      <Page key={milestoneIndex} size="A4" style={styles.page}>
        <Text style={styles.weekHeader}>
          Week {milestone.week}: {milestone.title}
        </Text>

        <View style={styles.section}>
          <Text style={styles.text}><Text style={{ fontWeight: 'bold' }}>Phase:</Text> {milestone.phase}</Text>
          <Text style={styles.text}>{milestone.description}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.subsectionTitle}>Learning Objectives</Text>
          {milestone.learningObjectives.map((obj, index) => (
            <Text key={index} style={styles.bulletPoint}>• {obj}</Text>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.subsectionTitle}>Tasks</Text>
          {milestone.tasks.map((task, taskIndex) => (
            <View key={taskIndex} style={styles.taskCard}>
              <Text style={styles.taskTitle}>{taskIndex + 1}. {task.title}</Text>
              <Text style={styles.taskMeta}>
                Type: {task.type.replace('_', ' ')} | Time: {task.estimatedHours}h | Priority: {task.priority}
              </Text>
              <Text style={styles.text}>{task.description}</Text>
              
              {task.resources.length > 0 && (
                <View style={{ marginTop: 4 }}>
                  <Text style={{ fontSize: 10, fontWeight: 'bold', marginBottom: 2 }}>Resources:</Text>
                  {task.resources.map((resource, resIndex) => (
                    <Text key={resIndex} style={styles.resourceLink}>
                      • {resource.title} ({resource.platform}){resource.isFree ? ' - Free' : ''}
                    </Text>
                  ))}
                </View>
              )}
              
              <Text style={[styles.text, { marginTop: 4 }]}>
                <Text style={{ fontWeight: 'bold' }}>Deliverable:</Text> {task.deliverable}
              </Text>
            </View>
          ))}
        </View>

        <View style={styles.section}>
          <Text style={styles.subsectionTitle}>Weekly Goal</Text>
          <Text style={styles.text}>{milestone.weeklyGoal}</Text>
        </View>

        <View style={styles.timeAllocation}>
          <View style={styles.timeItem}>
            <Text style={{ fontWeight: 'bold' }}>{milestone.timeAllocation.learning}h</Text>
            <Text>Learning</Text>
          </View>
          <View style={styles.timeItem}>
            <Text style={{ fontWeight: 'bold' }}>{milestone.timeAllocation.practice}h</Text>
            <Text>Practice</Text>
          </View>
          <View style={styles.timeItem}>
            <Text style={{ fontWeight: 'bold' }}>{milestone.timeAllocation.projects}h</Text>
            <Text>Projects</Text>
          </View>
          <View style={styles.timeItem}>
            <Text style={{ fontWeight: 'bold' }}>{milestone.timeAllocation.networking}h</Text>
            <Text>Networking</Text>
          </View>
        </View>

        <Text style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} fixed />
      </Page>
    ))}

    {/* Final Page - Success Metrics & Tips */}
    <Page size="A4" style={styles.page}>
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Success Metrics</Text>
        {roadmap.successMetrics.map((metric, index) => (
          <Text key={index} style={styles.bulletPoint}>• {metric}</Text>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Pro Tips</Text>
        {roadmap.tips.map((tip, index) => (
          <Text key={index} style={styles.bulletPoint}>• {tip}</Text>
        ))}
      </View>

      <Text style={styles.footer}>Generated by RoadmapAI - Your AI Career Architect</Text>
      <Text style={styles.pageNumber} render={({ pageNumber }) => `Page ${pageNumber}`} fixed />
    </Page>
  </Document>
);
